"""empty message

Revision ID: e8b1e50c98a6
Revises: 
Create Date: 2023-11-15 06:56:01.645057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b1e50c98a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('adress', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description1', sa.Text(), nullable=True),
    sa.Column('description2', sa.Text(), nullable=True),
    sa.Column('description3', sa.Text(), nullable=True),
    sa.Column('description4', sa.Text(), nullable=True),
    sa.Column('description5', sa.Text(), nullable=True),
    sa.Column('rentaltime', sa.Text(), nullable=True),
    sa.Column('bukkinngnorma', sa.Text(), nullable=True),
    sa.Column('janre', sa.Text(), nullable=True),
    sa.Column('booking_live', sa.Text(), nullable=True),
    sa.Column('hall_rental_details', sa.Text(), nullable=True),
    sa.Column('one_drink_price', sa.Text(), nullable=True),
    sa.Column('secondary_use', sa.Text(), nullable=True),
    sa.Column('streaming_live_available', sa.Text(), nullable=True),
    sa.Column('picture1', sa.String(length=255), nullable=True),
    sa.Column('picture2', sa.String(length=255), nullable=True),
    sa.Column('picture3', sa.String(length=255), nullable=True),
    sa.Column('picture4', sa.String(length=255), nullable=True),
    sa.Column('picture5', sa.String(length=255), nullable=True),
    sa.Column('picture6', sa.String(length=255), nullable=True),
    sa.Column('picture7', sa.String(length=255), nullable=True),
    sa.Column('picture8', sa.String(length=255), nullable=True),
    sa.Column('picture9', sa.String(length=255), nullable=True),
    sa.Column('picture10', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('content')
    op.drop_table('article')
    # ### end Alembic commands ###
